### PR TITLE
Tweaks

### PR DESCRIPTION
**Pull request by XhmikosR**
Too lazy to split this :)

### CODE REVIEW

**Comment by XhmikosR** [comment]
Oops, sorry, I updated deps too without seeing #10

**Comment by pierreinglebert** [comment]
"Too lazy to split this :)"
You saw how lazy I was just to update dependencies :D

**Comment by XhmikosR** [comment]
Feel free to merge yours and I'll rebase this. :)

**Comment by XhmikosR** [comment]
I might need to fix the build so, just merge yours and I'll have a look later or tomorrow.

**Comment by XhmikosR** [comment]
@pierreinglebert: should be ready now, wait for Travis and merge if it passes.

**Comment by pierreinglebert** [comment]
Why do remove .npmignore ? I think we should at least keep test folder and some dotfiles in it.

**Comment by XhmikosR** [comment]
Because it's much better specifying what to keep. https://github.com/pierreinglebert/grunt-zopfli-native/pull/11/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R45

**Comment by pierreinglebert** [comment]
oh ! didn't see this, my bad, sorry.

**Comment by XhmikosR** [comment]
Wait a sec, I found that prettybytes is unused, let me remove it.

**Comment by XhmikosR** [comment]
Done.

**Comment by XhmikosR** [comment]
Updated.

**Comment by pierreinglebert** [comment]
Thank you !

**Pull request merged**
